import math as m
# print(m.ceil(3.6))
# print(m.floor(3.4))
# print(m.trunc(3.4))
# print(m.trunc(3.6))
# print(round(3.4))
# print(m.factorial(6))
# print(m.gcd(4,6))
# print(m.lcm(4,6))
print(m.sin(90))
# print(m.cos(0))
# print(m.tan(45))
print(m.fmod(10,3))