s={1,2,3,4}
s1={2,4,6}
print(s.union(s1))
print(s|s1)
print(s.intersection(s1))
print(s&s1)
print(s.difference(s1))
print(s-s1)
print(s1-s)
print(s.symmetric_difference(s1))
print(s1.symmetric_difference(s))